### ISSUE TITLE
Feature request: faster crossprod and tcrossprod

### ISSUE THREAD

**Issue by ajabadi** [RfastOfficial/Rfast#10]
It would be nice to allow transposition to be handled in `mat.mult` variants so one doesn't have to inefficiently do `mat.mult(x, t(y))` or `mat.mult(t(x), y)`as for large matrices `t()` can be quite inefficient and a bottleneck for `mat.mult`.

**Comment by ManosPapadakis95** [comment]
t() in R is quite fast! Even for large matrices. Although I have a faster cross and tcross which is not exported yet.

**Comment by ManosPapadakis95** [comment]
Done. The new functions "Crossprod" and "Tcrossprod" will be added in the next update of Rfast2.
