### ISSUE TITLE
Feature request: shuffle

### ISSUE THREAD

**Issue by mayer79** [RfastOfficial/Rfast#11]
Idea: Add Fisher-Yates' (std::shuffle or std::random_shuffle) algorithm to generate random permutations. Currently, the "R way" to shuffle a vector x is to call `sample(x)`, which is not optimized for that case. 

Using a state of the art and seedable random number generator would be great.

Here is a rcpp version that uses "std::random_shuffle":
https://gallery.rcpp.org/articles/stl-random-shuffle/index.html

**Comment by ManosPapadakis95** [comment]
colShuffle uses std::shuffle and random engine (which is not good to use). Unfortunately std::random is not faster than sample... That's why is not exported in Rfast.

**Comment by mayer79** [comment]
I see. 

Actually, at least for larger vectors, `colShuffle` is faster than `sample`:

```
library(Rfast)
library(microbenchmark)

set.seed(3)
x <- rnorm(1e6)

microbenchmark(sample(x),
               colShuffle(cbind(x)),
               times = 3)

# Unit: milliseconds
#                  expr      min       lq     mean   median       uq      max neval
#             sample(x) 328.4082 331.6087 334.0163 334.8092 336.8203 338.8315     3
# colShuffle( cbind(x))  93.1315  99.5063 105.1291 105.8811 111.1278 116.3746     3
```

So it is only about the use of a good rng (ideally seedable or we could pass an integer seed if it is easier)?

https://meetingcpp.com/blog/items/stdrandom_shuffle-is-deprecated.html

**Comment by ManosPapadakis95** [comment]
Sory, I forgot it... I have a faster sample for integer and numeric using another RNG. Please wait for the next update but I will add them in Rfast2.

**Comment by mayer79** [comment]
Nice!
