### ISSUE TITLE
Dist() error with canberra method

### ISSUE THREAD

**Issue by thdevilee** [RfastOfficial/Rfast#111]
**Describe the bug**
Dist() gives an error when the method has been set to canberra

**To Reproduce**
```
set.seed(42)
Dist(matrix(rnorm(20), ncol = 2, nrow = 10), method = 'canberra')
```

Error:
```
Error: Mat::col(): index out of bounds
```

**Desktop:**
 - OS: Windows 11 64-bit
 - R-Version 4.3.0
 - Rfast-Version 2.1.0

**Additional context**
The error always seems to appear, independent of the input matrix

**Comment by ManosPapadakis95** [comment]
Already solved in #103.
