### ISSUE TITLE
Can't sample using rvmf() with k=0

### ISSUE THREAD

**Issue by mbojan** [RfastOfficial/Rfast#114]
**Describe the bug**
Can't sample uniformly using `rvmf()`

**To Reproduce**
``` r
Rfast::rvmf(3, c(0,0,0), 0)
#> Error in eval(expr, envir, enclos): element-wise division: incompatible matrix dimensions: 3x3 and 3x1
```
but this works

```r
Rfast::rvmf(3, 0, 0)
##      [,1]
## [1,]    1
## [2,]    1
## [3,]    1
```

**Expected behavior**

Works.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - R-Version: 4.4.1
 - Rfast-Version 2.1.0
 - GCC-Version 11.4.0

**Comment by statlink** [comment]
Hi Mbojan, the problem is with the mu vector. The mu must be a unit vector, so the coordinates you give, c(0,0,0), do not lie on the sphere.

**Comment by statlink** [comment]
We also thank you @mbojan for noticing the problem with k=0.
