### ISSUE TITLE
Cosine method in Rfast::Dist returns a similarity matrix, not a distance

### ISSUE THREAD

**Issue by nigiord** [RfastOfficial/Rfast#119]
**Describe the bug**

When using `Rfast::Dist()` with the argument `method = "cosine"`, the output is a similarity distance with the diagonal set to 0.

**To Reproduce**

```R
> m <- matrix(c(1,2,3,1,2,3,3,2,1), nrow=3, byrow=TRUE)
> m
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    1    2    3
[3,]    3    2    1
> Rfast::Dist(m, method = "cosine")
          [,1]      [,2]      [,3]
[1,] 0.0000000 1.0000000 0.7142857
[2,] 1.0000000 0.0000000 0.7142857
[3,] 0.7142857 0.7142857 0.0000000
```

**Expected behavior**

The result should be:
```
          [,1]      [,2]      [,3]
[1,] 0.0000000 0.0000000 0.2857143
[2,] 0.0000000 0,0000000 0.2857143
[3,] 0.2857143 0.2857143 0.0000000
```

**Desktop (please complete the following information):**
 - OS: Linux 64bits
 - R-4.3.3
 - Rfast-2.1.0
 - GCC-8.5.0

**Additional context**

The formula given in the documentation of the `Rfast::Dist()` states:

```raw
cosine : \sum (P_i * Q_i) / \sqrt(\sum P_i^2) * \sqrt(\sum Q_i^2)
```

This is indeed the formula for the **cosine similarity**. But the function is supposed to return a distance for all methods:

```raw
Value

A square matrix with the pairwise distances. 
```

The fact that the diagonal is still 0 is rather misleading... Took me some time to realize that I was actually dealing with a similarity matrix (and not a distance matrix as expected).

**Suggested fix**

Return `1 - current_result` (keeping the diagonal at 0) and fix the documentation to 

```raw
cosine : 1 - (\sum (P_i * Q_i) / \sqrt(\sum P_i^2) * \sqrt(\sum Q_i^2))
```
```

**Comment by nigiord** [comment]
Hi @ManosPapadakis95 , I’m not sure if this was fixed or not? I tested the same example with version 2.1.4 but the result is now:
```r
> m <- matrix(c(1,2,3,1,2,3,3,2,1), nrow=3, byrow=TRUE)
> m
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    1    2    3
[3,]    3    2    1
> Rfast::Dist(m, method = "cosine")
          [,1]      [,2]      [,3]
[1,] 0.0000000 0.0000000 0.5714286
[2,] 0.0000000 0.0000000 0.5714286
[3,] 0.5714286 0.5714286 0.0000000
```

It does not seem right. If I apply the formula for cosine distance I obtain 0.2857143:

```r
> u <- c(1, 2, 3)
> v <- c(3, 2, 1)
> 1 - (sum(u*v) / (sqrt(sum(u^2)) * sqrt(sum(v^2))))
[1] 0.2857143
```

**Comment by statlink** [comment]
Hi nigiord. 
Manos is right and I have checked it also. The wikipedia definition you mentioned is the correct one. 
Suppose you normalize the vectors first, u' = u / sqrt( sum(u^2) ) and v' = v / sqrt( sum(v^2) ) and then compute the squared Euclidean distance on the unit vectors the result is the same. You did not multiply by 2. 
But, you have a point, the help file has the wrong formula. It should be 2*(1 - Σ...). We will fix this typo in the formula in the next update and highlight that this is the squared version.
