### ISSUE TITLE
wrong calculation of "colMins"

### ISSUE THREAD

**Issue by XiaoruiZhu** [RfastOfficial/Rfast#13]
> test1 <- matrix(c(1,0,1,0,1,0.000009), 2,3, byrow = F)
```
#         [,1] [,2]  [,3]
# [1,]    1    1 1e+00
# [2,]    0    0 9e-06
```
> colMins(test1) # Gives wrong values

`# 2 2 2`

**Comment by statlink** [comment]
Why is this a mistake? For each column you want the position of the minimum value. If you want the value, then type colMins(set1, value=TRUE)
