### ISSUE TITLE
Argument `n` for rowMins and rowMaxs

### ISSUE THREAD

**Issue by thiagoveloso** [RfastOfficial/Rfast#15]
Thanks for the wonderful package.

Currently, `rowMins` and `rowMaxs` return respectively only the minimum and maximum values for each row.

It would be great to add an `n` argument to those functions, which would return the `n` (for example 5) smallest and largest numbers for each row.

As a result of the example above, 5 values would be returned for each row (and not just the 5th value). Does that feature sound useful for you guys as well?

**Comment by ManosPapadakis95** [comment]
Actually you want a partial sorting. I already have this algorithm in colSort but not in cran yet. You can see a similar usage in Sort using argument partial.

**Comment by thiagoveloso** [comment]
> Actually you want a partial sorting. I already have this algorithm in colSort but not in cran yet. You can see a similar usage in Sort using argument partial.

Cool! Looking forward to testing that functionality. Any ideia on when will it be on Cran?

**Comment by ManosPapadakis95** [comment]
Unfortunately, in a few months.

**Comment by ManosPapadakis95** [comment]
Done. But this feature will be added in colnth and rownth functions choosing the number of the returned values. For matter of speed the values will be sorted.
