### ISSUE TITLE
Rfast causes R to hang

### ISSUE THREAD

**Issue by jkeuskamp** [RfastOfficial/Rfast#16]
using the rowMins function causes the 'Rsession' process to become unstable. Within a short period of time after using rowMins, R becomes unresponsive without obvious reason. It always happens upon execution of a statement, but it doesn't seem exactly reproducable i.e. sometimes the same run of statements may run fine, while other times it hangs immediately.

This problem makes this package unusable in my case.
This problem occurred with the latest version of base (3.6.3) installed on macOS 10.15.2 with the following packages loaded:

```
"base"       "data.table" "datasets"   "dplyr"      "dtplyr"     "forcats"    "ggplot2"    "graphics"  
"grDevices"  "lubridate"  "methods"    "openxlsx"   "pacman"     "progress"   "purrr"      "readr"     
"readxl"     "recipes"    "stats"      "stringr"    "tibble"     "tibbletime" "tidyr"      "tidyverse" 
"timetk"     "units"      "utils"      "xts"        "zoo"
```

**Comment by ManosPapadakis95** [comment]
Can you give me the examples that crashed R?

**Comment by jkeuskamp** [comment]
Seems to be completey random, even dim(df) crashed Rsession at as some point.

**Comment by ManosPapadakis95** [comment]
It crashes in a specific command that you use rowMins? That doesn't make any sense. If you can't reproduce error then it might not be Rfast's problem. We have checked the function and it works perfectly. Any idea what to do?

**Comment by jkeuskamp** [comment]
Rsession crashes within minutes after using rowMins, even if I do not load the Rfast package. Although it always crashes upon execution of an expression, there is seemingly no pattern in what expressions are used.

I a report of a very similar (the same?) issue on the CRAN copy of Rfast:
https://github.com/cran/Rfast/issues/2. At this moment I am not in the position to construct a reproducable example, but I may try and do so at a later time.

**Comment by ManosPapadakis95** [comment]
I don't know how to help.... If you find any example that R crashes let me know.

**Comment by tjfarrar** [comment]
I am also having some such problems. For instance, if I call

`Rfast::mat.mult(diag(4), diag(5))` 
it not only throws an error (as it should) but crashes the R session. I am running R version 3.6.2 (64-bit) on Windows 8. I tried also in R-devel with same result. It happens in RStudio and in RGui.

Even some matrices with conformable dimensions also caused such a crash. For example, 
`X <- matrix(data = runif(100 * 2), nrow = 100, ncol = 2)`
`Rfast::mat.mult(Rfast::transpose(X), X)`

The error thrown is 

> Mat::col(): index out of bounds

The R session crashes with a dialogue:

> Runtime Error! Rgui.exe This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

Maybe this is not an issue with your package per se, but I have never had this happen with any other R function.

**Comment by ManosPapadakis95** [comment]
> I am also having some such problems. For instance, if I call
> 
> `Rfast::mat.mult(diag(4), diag(5))`
> it not only throws an error (as it should) but crashes the R session. I am running R version 3.6.2 (64-bit) on Windows 8. I tried also in R-devel with same result. It happens in RStudio and in RGui.
> 
> Even some matrices with conformable dimensions also caused such a crash. For example,
> `X <- matrix(data = runif(100 * 2), nrow = 100, ncol = 2)`
> `Rfast::mat.mult(Rfast::transpose(X), X)`
> 
> The error thrown is
> 
> > Mat::col(): index out of bounds
> 
> The R session crashes with a dialogue:
> 
> > Runtime Error! Rgui.exe This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
> 
> Maybe this is not an issue with your package per se, but I have never had this happen with any other R function.

I have already fix this bug for the next update.

**Comment by tjfarrar** [comment]
> I have already fix this bug for the next update.
When can we expect the next update on CRAN? Is it possible to make the development version available on Github in the meantime? I see that it is still only version 1.9.9 that is available on Github (same as on CRAN).

**Comment by tjfarrar** [comment]
> I have already fix this bug for the next update.

When can we expect the next update on CRAN? Is it possible to make the development version available on Github in the meantime? I see that it is still only version 1.9.9 that is available on Github (same as on CRAN).

**Comment by ManosPapadakis95** [comment]
> > I have already fix this bug for the next update.
> 
> When can we expect the next update on CRAN? Is it possible to make the development version available on Github in the meantime? I see that it is still only version 1.9.9 that is available on Github (same as on CRAN).

I don't know...  Download github version. I have fix it.

**Comment by tjfarrar** [comment]
Thanks. A suggestion would be to follow the naming conventions for development versions of a package, e.g. 1.9.9.9001. See [here](http://r-pkgs.had.co.nz/description.html#version). Otherwise people will assume that version 1.9.9 on Github is identical to version 1.9.9 on CRAN.

**Comment by nassuphis** [comment]
rowOrder() still causes a crash, i used the github version

**Comment by ManosPapadakis95** [comment]
That's doesn't make any sense. I have the same version of rowOrder for a
long time. Could you please kindly check it again?

Στις Σάβ, 30 Ιαν 2021, 18:25 ο χρήστης nassuphis <notifications@github.com>
έγραψε:

**Comment by nassuphis** [comment]
on it. will report back once i have a repeatable example.
