### ISSUE TITLE
Rfast::Dist() causes Rstudio-Tab call of doc to freeze the app until kill

### ISSUE THREAD

**Issue by Melkiades** [RfastOfficial/Rfast#19]
So, it has been a nightmare because it is very hardly reproducible and it was since a bit I added Rfast (which is incredibly fast, thanks for that :) ) to my work pipeline. This freezing happens on Ubuntu 18.04 LTS and Mac OS X catalina with the latest versions of R, Rfast, Rstudio and tidyverse. To reproduce the error, it is enough to run `Rfast::Dist()` or to attach the pkg to the environment and to Tab complete a function from tidyverse like mutate_all and this freezes Rstudio completely! 

I hope it is reproducible with this degree of precision! I do not know what is the problem, but could it be a documentation related loop? maybe related to the fact that Dist is too similar to the rbase dist?

Thank you for your time and sorry if the problem was already, for some to me unknown reasons, solved.

**Comment by ManosPapadakis95** [comment]
Can you give me an example? I have never use tidyverse package...

**Comment by Melkiades** [comment]
yes, it is enough to run the following: `library(Rfast); library(tidyverse)` and then take a function like `mutate_all()` and try to tab-complete it and to press again tab to call the function variable documentation and Rstudio freezes until killing. This is somehow connected with Rstudio because just from terminal it is not freezing the session.

**Comment by statlink** [comment]
Hi Melkiades, this is Michail. I tried what you said in R and it works perfectly fine. But, when I pressed the "tab" in Rstudio it jammed. I will agree with you, this has something to do with Rstudio.

**Comment by ManosPapadakis95** [comment]
I test it in my laptop with last version of R and Rstudio and it works fine. Maybe it is Rstudio.

**Comment by Melkiades** [comment]
> I test it in my laptop with last version of R and Rstudio and it works fine. Maybe it is Rstudio.

I sincerely doubt it. I made a video of what still happens in R 4.0.0 (version of 5 days ago), Rstudio 1.2.5042 (latest version, 28 days ago). Also, I run everything on the latest Catalina (10.15.4). In addition, the problem is still present also on Rstudio server and on Ubuntu 18.04 LTS.

I attach a 1 min video that can show you what happens (what you do not see is that I press tab many times).


![Untitled](https://user-images.githubusercontent.com/11279768/80609937-003d2e80-8a39-11ea-8436-604b3251c046.gif)

**Comment by ManosPapadakis95** [comment]
> > I test it in my laptop with last version of R and Rstudio and it works fine. Maybe it is Rstudio.
> 
> I sincerely doubt it. I made a video of what still happens in R 4.0.0 (version of 5 days ago), Rstudio 1.2.5042 (latest version, 28 days ago). Also, I run everything on the latest Catalina (10.15.4). In addition, the problem is still present also on Rstudio server and on Ubuntu 18.04 LTS.
> 
> I am aware it is not directly your problem, but, as they said the problem is still present in the dev version of Rstudio 1.3 and as many of us code using Rstudio, I would keep this issue open. I mean it is completely impossible to use Rfast on Rstudio... must be something to keep an eye on isn't it?
> 
> I attach a 1 min video that can show you what happens (what you do not see is that I press tab many times).
> 
> ![Untitled](https://user-images.githubusercontent.com/11279768/80609937-003d2e80-8a39-11ea-8436-604b3251c046.gif)

In my laptop it is fine. Tidyverse shows conflicts about same functions on different packages. Personally in C++ it is a bad practice to use library mechanism because of those conflicts. Although I use it for readability. These conflicts might be the problem. Generally, when I run library ("tidyverse") it took one minute to finish. Jesus... A lot of time for a small thing... But it checks for a lot of things as you see. Sometime, I waited and I thought that there is a problem but eventually it just needed time. I don't know what to tell you...
