### ISSUE TITLE
Odd results from mat.mult function

### ISSUE THREAD

**Issue by tjfarrar** [RfastOfficial/Rfast#20]
I am trying to use the package to speed up some computations relating to linear regression diagnostics. Specifically I wanted a faster way to compute the "annihilator matrix" or "projection matrix," M. This would be computed using base functions as follows:

```
n <- 10
p <- 2
X <- cbind(1, matrix(data = runif(n * p), nrow = n, ncol = p))
M <- diag(n) - X %*% solve(crossprod(X)) %*% t(X)
```

Now, I tried to compute M using Rfast functions as follows:
```
library(Rfast)
Mfast <- diag(n) - mat.mult(mat.mult(X, spdinv(crossprod(X))), transpose(X))
```
This throws an error, "non-conformable arrays." It turns out that the result of `mat.mult(mat.mult(X, spdinv(crossprod(X))), transpose(X))` is not, as expected, an n-by-n matrix, but rather a 3-by-n matrix of 0's.

It appears that `spdinv(crossprod(X))` produces the correct result, but `mat.mult(X, spdinv(crossprod(X)))` produces a 3-by-3 result where it should be an n-by-3 result.

Am I missing something? Note: I also tried writing Mfast using the pipe operator from package `magrittr`, with the same result:

`Mfast <- diag(n) - (spdinv(crossprod(X)) %>% mat.mult(x = X) %>% mat.mult(y = transpose(X)))`

**Comment by ManosPapadakis95** [comment]
We have already fix this bug in mat.mult for the next update.
