### ISSUE TITLE
Rfast::mat.mult is slower than base matrix multiplication function %*%

### ISSUE THREAD

**Issue by tjfarrar** [RfastOfficial/Rfast#22]
I have installed the current development version of `Rfast` from Github which contains a bug fix for function `mat.mult`. However, it seems that the `mat.mult` function is now much slower than the `%*%` function of base:
`A <- matrix(1:12, nrow = 4, ncol = 3, byrow = TRUE)`
`B <- matrix(1:15, nrow = 3, ncol = 5, byrow = TRUE)`
`system.time(replicate(1e4, mat.mult(A, B)))`
user  system elapsed
    2.2     3.1     3.7 
`system.time(replicate(1e4, A %*% B))`
user  system elapsed
   0.03    0.00    0.03

Similarly, it appears that `transpose` function is slower than the `t` function of base:
`system.time(replicate(1e4, transpose(A)))`
 user  system elapsed 
   0.34    0.59    0.67 
`system.time(replicate(1e4, t(A)))`
   user  system elapsed 
   0.06    0.00    0.06

**Comment by ManosPapadakis95** [comment]
You matrices are quite small... Unfortunately transpose and mat.mult are faster than R's for big matrices. The reason is that these functions run in parallel.

**Comment by tjfarrar** [comment]
Okay, I understand, thanks.
