### ISSUE TITLE
mat.mult yields wrong results

### ISSUE THREAD

**Issue by strsek** [RfastOfficial/Rfast#25]
Hi, I'd like to use the mat.mult function to multiply large matrices, but there seems to be some kind of issue.  See for instance:

     a <- matrix(1:9,3,3)
     b <- matrix(9:1, 3, 3)
     mat.mult(a,b)

which yields

                     [,1]          [,2]          [,3]
       [1,] 5.670082e-309 3.543801e-309 1.417520e-309
       [2,] 6.256907e-309 4.171266e-309 2.085625e-309
       [3,] 4.744127e-311 2.710930e-311 6.777325e-312

Thanks,
Stefan

**Comment by ManosPapadakis95** [comment]
This issue has been fixed.

**Comment by strsek** [comment]
Thanks!
