### ISSUE TITLE
print.environment interferes with dplyr

### ISSUE THREAD

**Issue by mpjdem** [RfastOfficial/Rfast#26]
After a few weeks of problems with RStudio randomly hanging, I tracked it down today to {Rfast}. As you can see [in this rstudio issue](https://github.com/rstudio/rstudio/issues/6645) the `print.environment()` function appears to not play nice with the {dplyr} namespace. RStudio is solving the problem on their end already, but I thought you might be interested in fixing this sort of infinite loop in {Rfast} as well:

```
library(Rfast)
dplyr <- asNamespace("dplyr")
print(dplyr)
```

**Comment by ManosPapadakis95** [comment]
I will look at it. thanks

**Comment by mjdufort** [comment]
I was also running into this problem intermittently, but could not trace it.  A collaborator helped me determine that it was based on a package using a single Rfast function (see issue [here](https://github.com/BenaroyaResearch/RNAseQC/issues/2)).  When I removed the Rfast dependency, the issue resolved.

I see this as a major issue, and I plan to cease using Rfast until it is resolved.  This is unfortunate, as the function I was using (Rfast::colTabulate) yields a dramatic speed-up to one of my processes.

**Comment by Azureuse** [comment]
Any idea on a timeframe for this bugfix? It makes Rfast essentially unusable (for me) at the moment. 

If you have a good idea of what's causing the issue I could try submitting a fix. Is it something to do with `print.environment` [link](https://github.com/RfastOfficial/Rfast/blob/master/R/s3operator.R#L83)? Could there be a circular reference causing an infinite recursion loop? 

When I experience the issue (which is frequently!) it hangs one cpu at 100% for 5-10mins until I get the "Error: C stack usage 7970996 is too close to the limit". 

I'm not actually sure what / when `print.environment` is used. Would adding a default recursion limit introduce any issues?

**Comment by ManosPapadakis95** [comment]
I will remove it in the next update. I am waiting for the Rfast2 to be
updated and then I will update Rfast.

Στις Παρ, 19 Μαρ 2021, 12:32 ο χρήστης Azureuse ***@***.***>
έγραψε:
