### ISSUE TITLE
Matrix multiplication does not work in my computer.

### ISSUE THREAD

**Issue by surya36** [RfastOfficial/Rfast#30]
Hello, I was using the Rfast package to do the following matrices, but I get the bad results as follows:
library(Rfast)
Loading required package: Rcpp
Loading required package: RcppZiggurat
>A = matrix(rnorm(50*40), 50, 40)
> B = matrix(rnorm(40*50), 40, 50)
> C = mat.mult(A,B)
> dim(C)
[1] 40 50
I get the size of the product as 40X50. One of my computers, it gives the right results. Can you suggest to me what could be the possible problem?

**Comment by ManosPapadakis95** [comment]
this error have been fixed. Please wait till next update

**Comment by gheager** [comment]
Is that bug fixed? I have installed Rfast yesterday and I have the same issue.

**Comment by ManosPapadakis95** [comment]
I haven't update Rfast yet... Please wait the next update...
