### ISSUE TITLE
Rfast on data.table

### ISSUE THREAD

**Issue by waynelapierre** [RfastOfficial/Rfast#33]
If I have a data.table whose numerical columns do not contain any missing values. I still need to convert it into a matrix to use Rfast. Are there any plans for making Rfast functions work on data.table? For most people, it is annoying to convert data to data.table and matrix back and forth all the time.

**Comment by ManosPapadakis95** [comment]
For now our plans is to support List and Dataframes in future versions. I have never used data.table so for supporting it I must do some research.

**Comment by waynelapierre** [comment]
data.table is the high-performance version of data.frame. if you could make Rfast work on data.frame, it should work on data.table as well.

**Comment by ManosPapadakis95** [comment]
I can work only with the structures that rcpp support. If it is a Dataframe then ok but you will get as result a dataframe that's for sure.

**Comment by waynelapierre** [comment]
A data.table is also a data.frame. If you check the class of a data.table, it will say both data.frame and data.table.
