### ISSUE TITLE
Add setting random seed in rmvnorm()

### ISSUE THREAD

**Issue by frederikziebell** [RfastOfficial/Rfast#36]
Setting a random seed with the base R method does not result in the same random number
```
set.seed(1)
Rfast::rmvnorm(1,0,1)
```
and one has to call `RcppZiggurat::zsetseed()`
```
RcppZiggurat::zsetseed(1)
Rfast::rmvnorm(1,0,1)
```
Maybe `rmvnorm()` could have an optional `seed` argument that just calls `RcppZiggurat::zsetseed()` for setting the random seed.

**Comment by ManosPapadakis95** [comment]
Yes you are right. We have the same problem for matrnorm so we will add a new function wrapper to ziggurat. Wait until next update. Thank you.
