### ISSUE TITLE
lmfit cannot deal with ill-conditioned design matrices

### ISSUE THREAD

**Issue by frederikziebell** [RfastOfficial/Rfast#37]
Consider the example 
```
n <- 50
x <- seq(1,500,len=50)
X <- cbind(1,x,x^2,x^3)
colnames(X) <- c("Intercept","x","x2","x3")
beta <- matrix(c(1,1,1,1),4,1)
set.seed(1)
y <- X%*%beta+rnorm(n,sd=1)
Rfast::lmfit(X,y)
```
which gives an error that the system is computationally singular. It's better to use a QR decomposition than directly inverting `crossprod(X)`, i.e. replace `solve(crossprod(X), crossprod(X, y))` with `solve(qr(X),y)`. If there is a vector of weights `w` or in general a weights matrix `W`, one has to convert the linear model first to a homoscedastic one via an eigen-decomposition as done in `MASS::lm.gls`

**Comment by statlink** [comment]
Hi frederikziebell.

If we were to make it via QR decomposition we would not achieve a high speed. You can see the code and regognize that it does not handle such cases as you mentioned. The purpose of Rfast is to make R fast. We let the user do the checks for his data. We give something that is bare bones and fast.

Michail

**Comment by frederikziebell** [comment]
Is is also slower

```
library("microbenchmark")
n <- 400
set.seed(1)
X <- matrix(rnorm(n^2),ncol=n)
beta <- 1:n
Y <- X%*%beta
microbenchmark(
  Rfast::lmfit(X,Y),
  solve(qr(X),Y),
  stats::lm.fit(X,Y)
)
```

![image](https://user-images.githubusercontent.com/28304028/101953131-1c719280-3bfa-11eb-9b56-e75056ffea44.png)

**Comment by statlink** [comment]
Yes, I will agree with you. I also tested in an old laptop. 

But, what kind of an example is this? Is this a realistic example? Who would perform a linear regression model with 400 variables if they had only 400 observations? Statistically it does not make too much sense. What if you try the same example with 50 variables? Is lmfit still slower? I think not. 

But, if this example suits you, then fine by me.
