### ISSUE TITLE
kruskaltest wrong result when x is a vector of zeros

### ISSUE THREAD

**Issue by boris-noyvert** [RfastOfficial/Rfast#39]
**Describe the bug**
Function kruskaltest(x, ina, logged = FALSE) when x is a vector of zeros produces wrong results. I would expect the p-value to be NA in this case (like the base R function kruskal.test does), however the p-value produced is very small (= very significant). This might affect results of statistical calculations.
Also 'kruskaltests' function is affected in the same way.

**To Reproduce**
> library(Rfast)
Loading required package: Rcpp
Loading required package: RcppZiggurat
> x=rep(0,100)
> ina=factor(sample(c("a","b","c"),100,replace = T))
> kruskaltest(x,ina)
        stat      p-value 
9.900000e+01 3.179971e-22 

**Expected behavior**
Both stat and p-value should be NA. This is the case when x is a constant vector, different from zero:

kruskaltest(x+1,ina)
   stat p-value 
    NaN     NaN 

Session info:
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS/LAPACK: /rds/bear-apps/2020a/Ubuntu16.04-haswell/software/OpenBLAS/0.3.9-GCC-9.3.0/lib/libopenblas_haswellp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfast_2.0.1        RcppZiggurat_0.1.6 Rcpp_1.0.4.6      

loaded via a namespace (and not attached):
[1] compiler_4.0.0 parallel_4.0.0 tools_4.0.0    tcltk_4.0.0

**Comment by statlink** [comment]
Hi Boris. 

The explanation is simple: when x = 0, the computations 
up <- sum(Rfast::group(R, ina)^2/ni) - n * (n + 1)^2/4
down <- sum(R^2) - n * (n + 1)^2/4
will compute the right parts, the summations are zero, but the second term in each line is a number. 
When x >0, both "up" and "down" are zero and you get the NA, which you should be obtaining when x = 0, or when x is a constant vector. So this means you are right. 

I repeat you are right. BUT, our philosophy is not to check the data. The user is suppost to check the data. We provide bare bone fast functions. We could of course could simply add this check (var(x) == 0).  This would imply that we should check all other functions and slowly add more checks and more checks and finally we deviate from our philosophy. For the "kruskaltests" for instance such a check would dramatically increase the computation time if the matrix is really large. So, we leave this checking part to the user. This is also written in the beginning of the manual. The user is responsible for the data. I will recognise though that unlike "kruskaltest", some functions are already robust and need no data check. But they are robust by nature, we did not robustify them. For instance ftest(x, ina) produces NA p-values for the example you mentioned.

**Comment by boris-noyvert** [comment]
Thank you, I agree with you and accept the speed arguments. I am closing the issue.
