### ISSUE TITLE
Consistent use of na.rm

### ISSUE THREAD

**Issue by waynelapierre** [RfastOfficial/Rfast#42]
colmeans does not have an na.rm argument while colMedian has one. It makes more sense to use it consistently. In addition, to make the Rfast functions applicable to data.frame, I think it is better to have an na.rm argument for all the functions. In my use case, most data have missing values.

**Comment by ManosPapadakis95** [comment]
Unfortunately we cannot do that. If a utility doesn't have na.rm it means that I wasn't able to find a faster version using na.rm. i am not the expert to answer about statisticalw functions.

**Comment by ManosPapadakis95** [comment]
Finally I have found a faster algorithm for na.rm in colmeans and colsums.
