### ISSUE TITLE
multi-thread support

### ISSUE THREAD

**Issue by waynelapierre** [RfastOfficial/Rfast#46]
**Is your feature request related to a problem? Please describe.**
The functions in Rfast seem to use only one core. It would be great if multi-thread support will be added. 

**Describe the solution you'd like**
Using OpenMP or RcppParallel would be the two approaches that I can think of.

**Describe alternatives you've considered**
Multi-thread support at R level by using the future.apply package seems OK but it does not always work on Windows OS.

**Comment by ManosPapadakis95** [comment]
The functions already use multi threaded using OpenMP library. Why do you think only one core is used?
