### ISSUE TITLE
rownth bug when na.rm = T even without integers. 

### ISSUE THREAD

**Issue by RodrigoZepeda** [RfastOfficial/Rfast#52]
**Describe the bug**
It seems that the `rownth` does not work when the `nth` value is the last one and `na.rm = T` returning the last column of the matrix instead. 

**To Reproduce**
You can check this one that doesn't have missing values but I've artificially set `na.rm = T`:

```{R}
mat <- matrix(as.numeric(c(1.1,2.1,3.1,
                           6.1,5.1,7.1,
                           9.1,10.1,8.1,
                           13.1,12.1,11.1,
                           15.1,16.1,14.1)), byrow = T, ncol = 3)
rownth(mat, rep(ncol(mat), nrow(mat)), na.rm = T)
```

Returns incorrectly:
```
3.1  7.1  8.1 11.1 14.1
```

The issue does not happen if `na.rm = F` which returns the correct values: 
```
3.1  7.1 10.1 13.1 16.1
```

**Expected behavior**
If no missing values `na.rm = F` and `na.rm = T` should be returning the same, right?

**Desktop (please complete the following information):**

```
platform       x86_64-apple-darwin20.6.0   
arch           x86_64                      
os             darwin20.6.0                
system         x86_64, darwin20.6.0        
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things              
```
 - Rfast-Version 2.0.3

**Comment by ManosPapadakis95** [comment]
Yes it is related and thank you very much for it.

**Comment by ManosPapadakis95** [comment]
No this is not related to #43 . Thank you very much. I just fix it.
