### ISSUE TITLE
Install issue with C++ 17 

### ISSUE THREAD

**Issue by mjrmason** [RfastOfficial/Rfast#54]
**Describe the bug**
I have problems installing Rfast. I get an error regarding C++17, the compiler version.

`* installing *source* package ‘Rfast’ ...
** package ‘Rfast’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error: C++17 standard requested but CXX17 is not defined`

**To Reproduce**
1. this is difficult to produce if not on the specific system

**Expected behavior**
1. installation with no issues

**Desktop (please complete the following information):**
 - OS: linux 
 - R-Version  4.0.2
 - Rfast-Version 2.0.4

**Additional context**
I have Rcpp, RcppZiggurat and RcppArmadillo installed.

**Comment by mjrmason** [comment]
I seemed to have resolved my issue by installing with 
`devtools::install_github("https://github.com/RfastOfficial/Rfast")`

**Comment by jitkang** [comment]
I am helping my university Research to install this in the server and encountered the same issue:

`C++17 standard requested but CXX17 is not defined`

However, I managed to install it by adding the following two lines into my `Makevars` file under `~/.R/Makevars`:

`CXX17=g++`
`CXX17STD= -fPIC -std=c++11`

Our servers is running CentOS 7.9 with GCC 4.8.5. I am not very familiar with how c++ works, but this seems to be related to the version of `g++` version being used. However, I do not have access to other machine with newer version of `g++` so I cannot confirm this.

**Comment by biostat0903** [comment]
Hi, 

I find the `Makeconf` file and add the code `CXX17=g++`  and `CXX17STD= -fPIC -std=c++11`. 
I use the default method to install R. The `Makeconf` file is in `/usr/local/R/lib64/R/etc`.

Best, 
Sheng

**Comment by ManosPapadakis95** [comment]
[Issue with C++17](https://stackoverflow.com/questions/47238577/target-requires-the-language-dialect-cxx17-with-compiler-extensions-but-cma). This link describes a way to fix this. You just have to update:

1. cmake
2. gcc

I believe this will solve the issue.
