### ISSUE TITLE
Setting the seed in knn.cv

### ISSUE THREAD

**Issue by merolagio** [RfastOfficial/Rfast#56]
Hi, thanks for the great package.

I would like to be able to set the seed in knn.cv.

I modified the ` generateFolds()` function changing at line 6

`set.seed(1234) to set.seed(seed)`

This assumes that seed can either be logical or numeric (if seed = TRUE -> set.seed(1)) and it works like a charm.

I hope this feature can be added in the next release

Many thanks

**Comment by statlink** [comment]
I fixed it Merolagio. 

You will see this in the next update.

**Comment by merolagio** [comment]
great, thanks
