### ISSUE TITLE
Bhattacharyya distance implementation

### ISSUE THREAD

**Issue by ioalan** [RfastOfficial/Rfast#61]
Could you please tell me the definition you used for the Bhattacharyya distance?

The code you used states: 
` a=sum(sqrt(abs(xv%xx.col(j))));`
where 
`xv=xx.col(i);`

Should it not be a product?
` a=sum(sqrt(abs(xv*xx.col(j))));`

from https://en.wikipedia.org/wiki/Bhattacharyya_distance 

Please correct me if I am wrong and thank you very much for making this great package!

**Comment by ManosPapadakis95** [comment]
Yes you are correct. I will add the references for all distances in the next update. Thank you very much. I will ask my partner to answer this because I am not sure.

**Comment by ManosPapadakis95** [comment]
Yes the correct is the product. Thanks again.
