### ISSUE TITLE
Error in zero variance in colVars()

### ISSUE THREAD

**Issue by myles-lewis** [RfastOfficial/Rfast#62]
I have noticed an odd bug in `colVars()` which can occur with a column of certain non-integers which are identical and thus should give var=0. I was hoping to use the function to detect var=0 in large numbers of columns.

Reproducible example:

```
x <- matrix(rep(2.897823, 60), ncol=1)
var(c(x))
## 0
Rfast::colVars(x)
## 1.830551e-14
matrixStats::colVars(x)
## 3.208926e-30
```

Any suggestions why?

**Comment by ManosPapadakis95** [comment]
Well, this is not a bug. The result is near to zero. In fact it can never be zero. The reason is the floating point arithmetic system. A solution to this would be to check if the variance is greater from ```1e-12``` then return zero.
