### ISSUE TITLE
Error: package or namespace load failed for ‘RcppGSL’ in dyn.load(file, DLLpath = DLLpath, ...):  unable to load shared object '/usr/lib64/R/library/00LOCK-RcppGSL/00new/RcppGSL/libs/RcppGSL.so':   libgsl.so.19: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by moschito78** [RfastOfficial/Rfast#64]
Hi at all, when a try to install Rfast on my R environment I received the error in the title. Somebody had the same issue?

**Comment by moschito78** [comment]
Hi Manos, my version is "R version 3.6.0 (2019-04-26) -- "Planting of a Tree""

**Comment by ManosPapadakis95** [comment]
I would suggest to update your version. Updating R means updating Rfast and these errors will fixed. The problem comes from RcppGSL unfortunately.
