### ISSUE TITLE
colRanks bug with method = "min"

### ISSUE THREAD

**Issue by jblood94** [RfastOfficial/Rfast#67]
**Describe the bug**
`colRanks` and `rowRanks` do not seem to behave correctly with `method = "min"`.
**To Reproduce Erroneous Results**
```
set.seed(1)
m <- matrix(runif(16), 4)
Rfast::colRanks(m, "min")
Rfast::colRanks(m, "max")
```

**Expected behavior**
The output of the two function calls should be identical.

**Desktop:**
 - OS: Windows 10 64-bit
 - R-Version 4.2.2
 - Rfast-Version 2.0.7

**Comment by ManosPapadakis95** [comment]
the bug have been fixed. The new version will be available in the next update. Thanks.
