### ISSUE TITLE
"harvesine" instead of "haversine"

### ISSUE THREAD

**Issue by coverton-usgs** [RfastOfficial/Rfast#68]
There is a typo in checking "harvesine" method instead of "haversine". I have fix it and it will be chabged from the next update.
For now you can safely just transpose the given argument.

_Originally posted by @ManosPapadakis95 in https://github.com/RfastOfficial/Rfast/issues/65#issuecomment-1436985796_
            
Can you explain "transpose the given argument"?

```
x <- matrix(rnorm(200), nrow = 100, ncol = 2)
d <- Dist(x, method = "harvesine")
```
Produces "Error: Unsupported Method: harvesine"

**Comment by ManosPapadakis95** [comment]
It is self explanatory. Give the matrix but first transposed it.

**Comment by coverton-usgs** [comment]
Sorry for being obtuse.

Just for clarity for the next hapless searcher

d <- Dist(t(x), method = "haversine")

**Comment by ManosPapadakis95** [comment]
Nobody said you are obtuse. 
This is a temporary solution anyway.
