### ISSUE TITLE
units for haversine distances in Dist 

### ISSUE THREAD

**Issue by aleksandrovivan** [RfastOfficial/Rfast#73]
I was using the haversine functionality of Dist to compute geographic distances matrix, and it was not entirely clear to me which units the inputs and outputs of the function are supposed to be in. 

It turns out both are in radians but it took me (and probably others who are coming from a geographic background) some time and simulations to establish that soundly, so a small clarification in the documentation file could be handy. Thank you!

**Comment by ManosPapadakis95** [comment]
Thanks for the information. We just forgot to add this specific detail.

**Comment by statlink** [comment]
Ivan hi. 

Is it ok now, is it clear?

Michail
