### ISSUE TITLE
ERROR: unable to collate and parse R files for package ‘Rfast’

### ISSUE THREAD

**Issue by Piccetteeno** [RfastOfficial/Rfast#75]
Hello,
I have a problem in installing Rfast: after I prompted `install.packages("Rfast")` it returns this error:

`g++-7 -std=gnu++17 -fPIC -shared -L/usr/local/lib -o Rfast.so Diag.o Norm.o Rank.o Sort.o Table.o add_to_namespace.o apply_condition.o as_integer.o binarysearch.o bincomb.o calc_qpois_regs.o check.o cholesky.o col_row_utilities.o col_row_utilities_p.o col_statistical.o colrint_mle.o colweibull_mle.o cts.o cts_rf.o design_matrix.o dir_knn.o diri_nr_type2.o dista.o dists.o dists_vec.o each.o eigs_sym_c.o energy.o floyd_john.o frame_to_matrix.o g2_export.o g2_helpers.o g2t.o gamma.o gaussian_nb.o geom_regs.o glm.o group.o hash.o init.o is.o k_nn.o logistic_only.o lower_upper_tri.o maha.o maha_ex.o matrices.o mn.o multinom_regs.o my_k_sorted_array.o normlog_reg.o normlog_regs.o odds_helper.o partial_sort.o pc_skel.o permutation.o positive_negative.o prop.o qpois.o rbing.o read.o reg_lib.o rep.o rint.o rmdp.o rvmf_h.o sf.o sort_mat.o sort_unique.o spat_med.o spml.o sw_regs.o system_files.o topological_sort.o total_dista.o total_dists.o utilities.o varcomps_mle.o vecdist.o weib_reg.o weibull_mle.o -L/home/nome/R-3.6.3/lib -lRlapack -L/home/nome/R-3.6.3/lib -lRblas -lgfortran -lm -lquadmath -fopenmp
installing to /home/nome/R-3.6.3/library/00LOCK-Rfast/00new/Rfast/libs
** R
Error in parse(outFile) : 
  /tmp/RtmpjLMToF/R.INSTALL123e52021c91/Rfast/R/onAttach.R:7:26: unexpected string constant
6:         msg <-  paste(
7:                         r"( ___ __ __ __ __    __ __ __ __ __ _             _               __ __ __ __ __     __ __ __ __ __ __   )"
                            ^
ERROR: unable to collate and parse R files for package ‘Rfast’
* removing ‘/home/nome/R-3.6.3/library/Rfast’

The downloaded source packages are in
	‘/tmp/RtmpULY1VA/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("Rfast") :
  installation of package ‘Rfast’ had non-zero exit status`

I am using:
Ubuntu 14.04
cmake 2.8.12.2
gcc  7.5.0

'R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.6 LTS

Matrix products: default
BLAS:   /home/nome/R-3.6.3/lib/libRblas.so
LAPACK: /home/nome/R-3.6.3/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppArmadillo_0.12.4.1.0 Rcpp_1.0.11             

loaded via a namespace (and not attached):
[1] compiler_3.6.3'

Any suggestion?

**Comment by ManosPapadakis95** [comment]
First of all upgrade R and gcc. R's current version is 4.3.1 and gcc 12+.
