### ISSUE TITLE
Error with Tcrossprod and very large matrices

### ISSUE THREAD

**Issue by fmorgante** [RfastOfficial/Rfast#78]
Hello,

When trying to use`Tcrossprod` with a very large matrix (~100,000 x ~100,000), I get the following error:

```
Error: Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
```

This is why https://arma.sourceforge.net/docs.html#config_hpp_arma_64bit_word.

Would it be possible for you to fix this?

**Comment by ManosPapadakis95** [comment]
Your computer is 32 or 64 bit?

**Comment by fmorgante** [comment]
64 bit

**Comment by ManosPapadakis95** [comment]
I cannot reproduce the error. I will look at it more and let you know.

**Comment by fmorgante** [comment]
Okay, thank you!

**Comment by ManosPapadakis95** [comment]
Fixed. Wait for next update.
