### ISSUE TITLE
Package dependency error

### ISSUE THREAD

**Issue by Shikari666** [RfastOfficial/Rfast#81]
When trying to install Rfast package,it shows dependency error and when trying to install those...it's not supporting the environment in Rstudio
ERROR: dependency ‘RcppZiggurat’ is not available for package ‘Rfast’
* removing ‘/home/vc514/R/x86_64-redhat-linux-gnu-library/4.3/Rfast’
Warning messages:
1: In i.p(...) :
  installation of package ‘RcppGSL’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘RcppZiggurat’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/RtmpsCHniD/file3499a17ff83c9/Rfast_2.0.8.tar.gz’ had non-zero exit status

_Originally posted by @Shikari666 in https://github.com/RfastOfficial/Rfast/issues/3#issuecomment-1741228400_

**Comment by ManosPapadakis95** [comment]
Have you tried to install RcppZiggurat?
