### ISSUE TITLE
Rfast::ttests not accepting an alternative parameter

### ISSUE THREAD

**Issue by MeisamYSF** [RfastOfficial/Rfast#90]
I am using ttests() to calculate two sample T tests for many samples, the default null hypothesis is "unequal" but I need to do "greater" or "lesser" tests which not available for the ttests() function while the same parameter can be tuned for one sample "ttest()". Is there a way to include the "alternative" parameter in the ttests() function as well?

**Comment by statlink** [comment]
Hi, yes, we can add it in some future update of the package.

**Comment by ManosPapadakis95** [comment]
Done.
