### ISSUE TITLE
Option to suppress warnings from Rcpp

### ISSUE THREAD

**Issue by Zhen-Miao** [RfastOfficial/Rfast#97]
**Is your feature request related to a problem? Please describe.**
I ran some evaluations of logistic regressions, and the warnings about *solve()* part are bothersome. The global warning suppression methods do not work for this as I guess they are warning messages from Cpp part. 

**Describe the solution you'd like**
I'd like to have a parameter in *glm_logistic()* for me to specify if I do not want these warnings.

**Comment by ManosPapadakis95** [comment]
Yes off course. I will add an extra parameter for every function that throws the warning which comes from Armadillo.

**Comment by ManosPapadakis95** [comment]
It seems that the mechanism for the streams is deprecate. There are two options:

1. Compile the ```Rfast``` and disable the errors using the configuration of ```Armadillo```
2. Use R code to catch the errors using the code:
```R
tryCatch(call_of_my_function, error = function(m){
   invisible()
})
```

**Comment by Zhen-Miao** [comment]
Thanks for your suggestions and I will try the second option (as it seems to be more straightforward). ;)
